version: '3.8'

services:
  messagebus:
    image: rabbitmq:latest
  api:
    build: ./api
    ports:
      - 3000:3000
    environment:
      MONGO_URL: "mongodb://mongo:27017"
      DB_NAME: "mydb"
      MESSAGE_QUEUE: "amqp://messagebus"
    deploy:
      restart_policy: 
        condition: on-failure
    depends_on:
      - mongo
      - messagebus
    links:
      - mongo
  frontend: 
    build: ./front-end
    ports:
      - 8080:8080
  mongo:
    image: mongo
    ports:
      - 27017:27017
    environment:
      ME_CONFIG_BASICAUTH_USERNAME: root
      ME_CONFIG_BASICAUTH_PASSWORD: root
      ME_CONFIG_MONGODB_PORT: 27017
    restart: always
    volumes:
      - ./docker-entrypoint-initdb.d/mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
  logging:
    build: './logging'
    environment:
      MESSAGE_QUEUE: "amqp://messagebus"
    volumes:
      - ./data:/data
    deploy:
      restart_policy: 
        condition: on-failure
    depends_on:
      - messagebus